# for open terminal in ubuntu use:
ctrl + alt + t

# for see wich directory we are use:
pwd

# for clear the shell use:
clear

# for list wich items are in the directory use:
ls

# for change directory use:
cd

# for see os info use:
uname

# for see details os info use:
uname -a

# for see help for commands use:
man

# for go to previous directory use:
cd ..

# for go to main directory use:
cd

# for make directory use:
mkdir

# for create file use:
touch

# for remove file use:
rm

# for remove directory use:
rm -rf

# for see all details of file or directory use:
ls -ltrh

# for see more details of files or directories use:
ls -l

# for see hidden files and directories use:
ls -a

# for see inside  use:
cat

# for set number for lines in cat use:
cat -n

# for see command history use:
history

# for display a line of text use:
echo

# for echo a text into a file use:
echo random_text >> file_name

# shell used to communicate user with kernel.

# root user have privilege to do anythink in os.

# for switch between users use:
su - username

# for know wich user we are login to system use:
whoami

# for run a command with root privilege use sudo before command.